
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fileprocessing-api:local
    container_name: fileprocessing-api
    restart: unless-stopped
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8085:8085"
  
